name: signspeech
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_database: ^12.0.0
  video_player: ^2.10.0
  cupertino_icons: ^1.0.8
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Tools for generating icons and splash screens
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0  # Moved here for best practice

flutter:
  assets:
   - assets/sample_video.mp4
   - assets/logo.png
  uses-material-design: true

# CONFIGURATION 1: App Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png" 
  min_sdk_android: 21

# CONFIGURATION 2: Splash Screen
flutter_native_splash:
  color: "#0288D1" 
  image: "assets/logo.png"
  ios_content_mode: "center"
  android_gravity: "center"